export const LOGIN_CUSTOMER = "LOGIN_CUSTOMER";
export const LOGIN_RESTAURANT = "LOGIN_RESTAURANT";
export const LOGOUT_CUSTOMER = "LOGOUT_CUSTOMER";
export const LOGOUT_RESTAURANT = "LOGOUT_RESTAURANT";