CREATE DEFINER=`root`@`localhost` PROCEDURE `SP_ADD_NEW_IMAGE`(IN R_ID INT,IN IMG VARCHAR(200),OUT ID INT )
BEGIN
 INSERT INTO RESTAURANT_IMAGES(REST_ID,IMAGE) VALUES(R_ID,IMG);
 set id=LAST_INSERT_ID();
END