CREATE DEFINER=`root`@`localhost` PROCEDURE `SP_ADD_NEW_ORDER`(IN R_ID INT,IN C_ID INT,IN O_STATUS VARCHAR(50), IN O_TYPE VARCHAR(50),OUT ID INT )
BEGIN
INSERT INTO ORDERS(REST_ID,CUST_ID,ORD_STATUS,ORD_TYPE) VALUES(R_ID,C_ID,O_STATUS,O_TYPE);
set id=LAST_INSERT_ID();
END