CREATE DATABASE IF NOT EXISTS UBER_EATS;
USE UBER_EATS;

CREATE TABLE IF NOT EXISTS RESTAURANT_USERS(
REST_ID int PRIMARY KEY auto_increment,
RNAME VARCHAR(100) NOT NULL,
EMAIL VARCHAR(60) NOT NULL,
PHONE VARCHAR(14),
PASS char(128) NOT NULL,
ADDRESS VARCHAR(120) NOT NULL,
ZIPCODE VARCHAR(5)
);
CREATE TABLE IF NOT EXISTS CUSTOMER_USERS(
CUST_ID INT AUTO_INCREMENT,
FNAME VARCHAR(50) NOT NULL,
LNAME VARCHAR(50) NOT NULL,
EMAIL VARCHAR(60) NOT NULL,
PASS CHAR(128) NOT NULL,
ADDRESS VARCHAR(120) NOT NULL,
ZIPCODE VARCHAR(5),
PRIMARY KEY(CUST_ID)
);
CREATE TABLE IF NOT EXISTS RESTAURANT_IMAGES(
	REST_ID INT,
    IMAGE_ID INT ,
    IMAGE BLOB,
    PRIMARY KEY (IMAGE_ID),
    FOREIGN KEY(REST_ID) REFERENCES RESTAURANT_USERS(REST_ID)
);
CREATE TABLE IF NOT EXISTS RESTAURANT_DISHES(
	REST_ID INT,
    DISH_ID INT,
    DISH_NAME VARCHAR (45) NOT NULL,
    INGREDIENTS VARCHAR(255) ,
    IMAGE BLOB,
    PRICE VARCHAR(5) NOT NULL,
    DISH_DESCR VARCHAR(255),
    CATEGORY INT NOT NULL,
    DISH_TYPE INT NOT NULL
    
);
CREATE TABLE IF NOT EXISTS ORDER_STATUS(
	ORD_STATUS INT PRIMARY KEY,
    ORD_DESC VARCHAR(45)
);
CREATE TABLE IF NOT EXISTS ORDER_TYPE(
	ORD_TYPE INT PRIMARY KEY,
    ORD_TYPE_DESC VARCHAR(45)
);
CREATE TABLE IF NOT EXISTS ORDERS(
	REST_ID INT,
    CUST_ID INT,
    ORDER_ID INT,
    ORD_STATUS INT,
    ORD_TYPE INT,
    PRIMARY KEY(ORDER_ID),
    FOREIGN KEY(CUST_ID) REFERENCES CUSTOMER_USERS(CUST_ID),
    FOREIGN KEY(REST_ID) REFERENCES RESTAURANT_USERS(REST_ID),
    #CAN ADD ORDER STATUS AND ORDER TYPE 
    FOREIGN KEY(ORD_STATUS) REFERENCES ORDER_STATUS(ORD_STATUS),
    FOREIGN KEY(ORD_TYPE) REFERENCES ORDER_TYPE(ORD_TYPE)
);
create table if not exists ORDERS_DETAILS(
	ORDER_ID int,
    ORDER_DET_ID INT PRIMARY KEY,
    #CAN BE FOREIGN KEY FOR DISH TABLE
    DISH_ID INT,
    DISH_QUANTITY INT,
    PRICE INT
);
