CREATE DATABASE IF NOT EXISTS UBER_EATS;
USE UBER_EATS;

CREATE TABLE IF NOT EXISTS RESTAURANT_USERS(
REST_ID int PRIMARY KEY auto_increment,
RNAME VARCHAR(100) NOT NULL,
EMAIL VARCHAR(60) NOT NULL unique,
PASS char(128) NOT NULL,
STREET VARCHAR(120) ,
CITY VARCHAR(40),
STATE VARCHAR(40),
COUNTRY varchar(40),
ZIPCODE VARCHAR(5),
PHONE VARCHAR(14),
RDESCRIPTION VARCHAR(255),
START_TIME VARCHAR(10),
END_TIME VARCHAR(10),
RDELIVERY_MODE VARCHAR(15)
);
CREATE TABLE IF NOT EXISTS CUSTOMER_USERS(
CUST_ID INT AUTO_INCREMENT,
FNAME VARCHAR(50) NOT NULL,
LNAME VARCHAR(50) NOT NULL,
EMAIL VARCHAR(60) NOT NULL unique,
PASS CHAR(128) NOT NULL,
NICKNAME VARCHAR(30),
ABOUT VARCHAR(120),
PROFILE_PIC varchar(150),
STREET VARCHAR(120),
CITY VARCHAR(30),
STATE VARCHAR(30),
COUNTRY varchar(40) ,
DOB varchar(10),
ZIPCODE VARCHAR(5),
PHONE VARCHAR(14),
PRIMARY KEY(CUST_ID)
);
-- CREATE TABLE IF NOT EXISTS CUSTOMER_PROFILE(
-- CUST_ID INT,
-- NICKNAME VARCHAR(30),
-- ABOUT VARCHAR(120),
-- PROFILE_PIC BLOB,
-- STREET VARCHAR(120),
-- CITY VARCHAR(30),
-- STATE VARCHAR(30),
-- COUNTRY INT ,
-- ZIPCODE VARCHAR(5),
-- FOREIGN KEY(CUST_ID) REFERENCES CUSTOMER_USERS(CUST_ID)
-- );

CREATE TABLE IF NOT EXISTS RESTAURANT_IMAGES(
	REST_ID INT,
    IMAGE_ID INT AUTO_INCREMENT,
    IMAGE varchar(150),
    PRIMARY KEY (IMAGE_ID),
    FOREIGN KEY(REST_ID) REFERENCES RESTAURANT_USERS(REST_ID)
);
CREATE TABLE IF NOT EXISTS RESTAURANT_DISHES(
	REST_ID INT,
    DISH_ID INT AUTO_INCREMENT PRIMARY KEY,
    DISH_NAME VARCHAR (45) NOT NULL,
    INGREDIENTS VARCHAR(255) ,
    IMAGE varchar(150),
    PRICE VARCHAR(5) NOT NULL,
    DISH_DESCR VARCHAR(255),
    CATEGORY VARCHAR(30) NOT NULL,
    DISH_TYPE VARCHAR(30) NOT NULL
    
);
CREATE TABLE IF NOT EXISTS ORDER_STATUS(
	ORD_STATUS INT PRIMARY KEY,
    ORD_DESC VARCHAR(45)
);
CREATE TABLE IF NOT EXISTS ORDER_TYPE(
	ORD_TYPE INT PRIMARY KEY,
    ORD_TYPE_DESC VARCHAR(45)
);
CREATE TABLE IF NOT EXISTS ORDERS(
	REST_ID INT,
    CUST_ID INT,
    ORDER_ID INT auto_increment,
    ORD_STATUS VARCHAR (50),
    ORD_TYPE VARCHAR (50),
    AMOUNT INT,
    DISH_DETAILS json,
    ORD_TIMESTAMP varchar(100),
    ORD_DEL_ADDRESS int,
    PRIMARY KEY(ORDER_ID),
    FOREIGN KEY(CUST_ID) REFERENCES CUSTOMER_USERS(CUST_ID),
    FOREIGN KEY(REST_ID) REFERENCES RESTAURANT_USERS(REST_ID)
    #CAN ADD ORDER STATUS AND ORDER TYPE 
    #FOREIGN KEY(ORD_STATUS) REFERENCES ORDER_STATUS(ORD_STATUS),
    #FOREIGN KEY(ORD_TYPE) REFERENCES ORDER_TYPE(ORD_TYPE)
);
create table if not exists ORDERS_DETAILS(
	ORDER_ID int,
    ORDER_DET_ID INT PRIMARY KEY,
    #CAN BE FOREIGN KEY FOR DISH TABLE
    DISH_ID INT,
    DISH_QUANTITY INT,
    PRICE INT
);

create table if not exists DELIVERY_ADDRESS(
	cust_id int,
    add_id int primary key auto_increment,
    cname varchar(50),
    address varchar(200),
    city varchar(100),
    zipcode varchar(10)
);

CREATE TABLE if not exists `customer_favourites` (
  `CUST_ID` int DEFAULT NULL,
  `REST_ID` int DEFAULT NULL,
  `FAV_ID` int NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`FAV_ID`)
) 


DELIMITER $$
CREATE DEFINER=`root`@`localhost` PROCEDURE `SP_Add_New_Customer`(in c_fname varchar(50),in c_lname varchar(50),in c_email varchar(60),in c_pass char(128),out id int)
BEGIN
	insert into customer_users(fname,lname,email,pass) values(c_fname,c_lname,c_email,c_pass);
    set id=LAST_INSERT_ID();
END$$
DELIMITER ;
DELIMITER $$
CREATE DEFINER=`root`@`localhost` PROCEDURE `SP_Add_New_Restaurant`(in r_name varchar(50),in r_add varchar(120), in r_city varchar(40),in r_state varchar(49),in r_zip varchar(5),in r_country varchar(40),in r_email varchar(60),in r_pass char(128),out id int)
BEGIN
	insert into RESTAURANT_USERS(rname,email,pass,street,city,state,country,zipcode) values(r_name,r_email,r_pass,r_add,r_city,r_state,r_country,r_zip);
    set id=LAST_INSERT_ID();
END$$
DELIMITER ;

DELIMITER $$
CREATE DEFINER=`root`@`localhost` PROCEDURE `SP_ADD_NEW_IMAGE`(IN R_ID INT,IN IMG VARCHAR(200),OUT ID INT )
BEGIN
 INSERT INTO RESTAURANT_IMAGES(REST_ID,IMAGE) VALUES(R_ID,IMG);
 set id=LAST_INSERT_ID();
END$$
DELIMITER ;

DELIMITER $$
CREATE DEFINER=`root`@`localhost` PROCEDURE `SP_ADD_NEW_DISH`(in rid int,in dname varchar(60),in ingre varchar(255),in dimg varchar(150),in dprice varchar(15),in ddesc varchar(255),in dcat VARCHAR(30),in dtype VARCHAR(30) ,out id int)
BEGIN
insert into restaurant_dishes (REST_ID,DISH_NAME,INGREDIENTS,IMAGE,PRICE,DISH_DESCR,CATEGORY,DISH_TYPE) VALUES (rid,dname,ingre,dimg,dprice,ddesc,dcat,dtype);
set id=LAST_INSERT_ID();
END$$
DELIMITER ;




